### PR TITLE
Fix missing Skaven prayers (fixes #1595)

### LINKED ISSUE #1595: [Skaven missing prayers]
Skaven

Prayer: Disease-Disease!

Prayer: Filth-filth!

Prayer: Rabid-rabid!

### PR DESCRIPTION
**Pull request by daviseford**

### CODE REVIEW

File: src/factions/skaven/subfactions.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ const subFactions = {
       endless_spells: [EndlessSpells],
       flavors: [Flavors],
       grand_strategies: [GrandStrategies],
-      Prayers: [Prayers],
+      prayers: [Prayers],
```
Comment (daviseford) [inline src/factions/skaven/subfactions.ts:26]: very naughty!
